feat: cache foundry dependencies

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -40,6 +40,9 @@ jobs:
       - name: Setup JS
         uses: ./.github/actions/js-setup
 
+      - name: Debug Foundry
+        run: anvil --version || echo "anvil not found"
+
       - name: Build
         run: pnpm run build-all
 
@@ -60,6 +63,9 @@ jobs:
       # Install and cache JS toolchain and dependencies (node_modules)
       - name: Setup JS
         uses: ./.github/actions/js-setup
+
+      - name: Debug Foundry
+        run: anvil --version || echo "anvil not found"
 
       - name: Test (preprod)
         run: anvil & pnpm run test-all && lsof -t -i tcp:8545 | xargs kill
@@ -88,6 +94,9 @@ jobs:
       # Install and cache JS toolchain and dependencies (node_modules)
       - name: Setup JS
         uses: ./.github/actions/js-setup
+
+      - name: Debug Foundry
+        run: anvil --version || echo "anvil not found"
 
       - name: Test (prod)
         run: anvil & pnpm run test-all && lsof -t -i tcp:8545 | xargs kill
